AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 130

Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - Gemfile

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Exclude:
    - config/application.rb
    - 'project_gems/keycloakr/test/**/*.rb'
    - 'spec/**/*_spec.rb'

Style/EmptyLiteral:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RedundantFetchBlock:
  Exclude:
    - config/puma.rb

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - config/environments/production.rb

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/WordArray:
  Enabled: false
