
production:
  clients:
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: <%= ENV['EDI_GATEWAY_DB_NAME'] %>
      hosts:
        - <%= ENV['EDI_GATEWAY_DB_HOST'] %>:<%= ENV['EDI_GATEWAY_DB_PORT'] %>
      options:
        <% if ENV['EDI_GATEWAY_DB_AUTH'] %>
        replica_set: <%= ENV['EDI_GATEWAY_DB_REPLICA_SET_NAME'] %>

        user: <%= ENV['EDI_GATEWAY_DB_USERNAME'] %>
        password: <%= ENV['EDI_GATEWAY_DB_PASSWORD'] %>
        auth_source: admin
       
        <% end %>
        write:
          w: 1
          j: true

    edidb:
      database: <%= ENV['EDIDB_DB_NAME'] %>
      hosts:
        - <%= ENV['EDIDB_DB_HOST'] %>:<%= ENV['EDIDB_DB_PORT'] %>
      options:
        <% if ENV['EDIDB_DB_AUTH'] %>
        replica_set: <%= ENV['EDIDB_DB_REPLICA_SET_NAME'] %>

        user: <%= ENV['EDIDB_DB_USERNAME'] %>
        password: <%= ENV['EDIDB_DB_PASSWORD'] %>
        auth_source: admin

        <% end %>

        write:
          w: 1
          j: true


