default: &default
  adapter: postgresql
  encoding: unicode
  # username: your username for your Postgresql access
  # password: your password for your Postgresql access
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  # development:
  #   <<: *default
  #   database: edi_gateway_development

  # test:
  #   <<: *default
  #   database: edi_gateway_test

  # production:
  #   <<: *default
  #   database: edi_gateway_production

development:
  adapter: postgresql
  encoding: unicode
  database: edi_gateway_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: edi_gateway_test
  pool: 5
